$("#loginbutton").click(function(){
    $("#loginModal").modal("show");
});
$("#buttonclose").click(function(){
    $("#loginModal").modal("hide");
});
$("#signup").click(function(){
    $("#SignupModal").modal("show");
});
$("#buttonclose1").click(function(){
    $("#SignupModal").modal("hide");
});